name: PR Size Check  # The name of the workflow

# Trigger the action on pull requests
on:
  pull_request:
    paths:
      - '**/*'  # This will monitor all files in the repository for changes

jobs:
  check_pr_size:  # Name of the job
    runs-on: ubuntu-latest  # This specifies the type of virtual machine to use for the job

    steps:
      - name: Checkout code  # Step to checkout the code from the PR branch
        uses: actions/checkout@v2  # GitHub Action to check out the code

      - name: Ensure the branch is up to date  # Step to update the branch
        run: |
          git fetch origin  # Fetch the latest changes from the remote repository

      - name: Calculate changes and check PR size  # Step to calculate added and deleted lines
        run: |
          # Calculate added lines
          added_lines=$(git diff --stat origin/main...test_branch | awk '{print $1}' | awk -F'+' '{print $2}' | grep -o '[0-9]\+' | awk '{s+=$1} END {print s}')
          
          # Calculate deleted lines
          deleted_lines=$(git diff --stat origin/main...test_branch | awk '{print $1}' | awk -F'-' '{print $2}' | grep -o '[0-9]\+' | awk '{s+=$1} END {print s}')
          
          # Total changes (added lines + deleted lines)
          total_changes=$((added_lines + deleted_lines))
          
          # Define the minimum and maximum threshold values
          MIN_THRESHOLD=10  # Minimum number of lines allowed
          MAX_THRESHOLD=500  # Maximum number of lines allowed
          
          # Compare the total changes with the thresholds
          if [ "$total_changes" -lt "$MIN_THRESHOLD" ] || [ "$total_changes" -gt "$MAX_THRESHOLD" ]; then
            echo "Pull request size is outside the allowed threshold range of $MIN_THRESHOLD - $MAX_THRESHOLD lines."
            exit 1  # Fail the action if the size is out of range
          else
            echo "Pull request size is within the acceptable range."
          fi

