name: PR Size Check  

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  check_pr_size:  
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Ensure the branch is up to date  
        run: |
          git fetch origin main

      - name: Calculate changes and check PR size
        run: |
          diff_stats=$(git diff --stat origin/main..HEAD)

          added_lines=$(echo "$diff_stats" | grep -o '\+.*' | awk -F'+' '{s+=$2} END {print s}')
          deleted_lines=$(echo "$diff_stats" | grep -o '\-.*' | awk -F'-' '{s+=$2} END {print s}')

          echo "Added lines: $added_lines"
          echo "Deleted lines: $deleted_lines"

          added_lines=${added_lines:-0}
          deleted_lines=${deleted_lines:-0}

          total_changes=$((added_lines + deleted_lines))

          echo "Total changes: $total_changes"

          MIN_THRESHOLD=10
          MAX_THRESHOLD=500

          if [ "$total_changes" -lt "$MIN_THRESHOLD" ] || [ "$total_changes" -gt "$MAX_THRESHOLD" ]; then
            echo "Pull request size is outside the allowed threshold range of $MIN_THRESHOLD - $MAX_THRESHOLD lines."
            exit 1 
          else
            echo "Pull request size is within the acceptable range."
          fi

