name: PR Size Check

on:
  pull_request:
    paths:
      - '**/*'  # Monitor all files

jobs:
  check-size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR size
        run: |
          # Ensure we're comparing the correct branches
          added_lines=$(git diff --stat origin/main...test_branch | awk '{print $1}' | awk -F'+' '{print $2}' | grep -o '[0-9]\+' | awk '{s+=$1} END {print s}')
          deleted_lines=$(git diff --stat origin/main...test_branch | awk '{print $1}' | awk -F'-' '{print $2}' | grep -o '[0-9]\+' | awk '{s+=$1} END {print s}')
          
          total_changes=$((added_lines + deleted_lines))
          
          MIN_THRESHOLD=10  # Minimum allowed changes
          MAX_THRESHOLD=500  # Maximum allowed changes

          # Compare with thresholds
          if [ "$total_changes" -lt "$MIN_THRESHOLD" ] || [ "$total_changes" -gt "$MAX_THRESHOLD" ]; then
            echo "Pull request size is outside the allowed threshold range of $MIN_THRESHOLD - $MAX_THRESHOLD lines."
            exit 1  # Fail the action if the size is out of range
          else
            echo "Pull request size is within the acceptable range."
          fi
