name: PR Size Check

# Trigger the action on pull requests
on:
  pull_request:
    paths:
      - '**/*'  # This will monitor all files in the repository

jobs:
  check-size:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Ensure the correct branches are fetched
      - name: Ensure correct branches are fetched
        run: |
          git fetch origin

      # Step 3: Check the number of lines changed in the PR
      - name: Check changes in PR
        run: |
          # Get the number of lines added and deleted in the pull request between origin/main and test_branch
          added_lines=$(git diff --shortstat origin/main...test_branch | grep -oP '\d+(?= insertions)' || echo 0)
          deleted_lines=$(git diff --shortstat origin/main...test_branch | grep -oP '\d+(?= deletions)' || echo 0)
          
          # Calculate total changes
          total_changes=$((added_lines + deleted_lines))

          # Define your threshold values
          MIN_THRESHOLD=10  # Minimum number of lines allowed
          MAX_THRESHOLD=500  # Maximum number of lines allowed

          # Compare the changes to the thresholds
          if [ "$total_changes" -lt "$MIN_THRESHOLD" ] || [ "$total_changes" -gt "$MAX_THRESHOLD" ]; then
            echo "Pull request size is outside the allowed threshold range of $MIN_THRESHOLD - $MAX_THRESHOLD lines"
            exit 1  # Fail the job if the size is out of range
          else
            echo "Pull request size is within the acceptable range."
          fi
